from typing import Protocol
from ..models import DataStore

class StoreRepository(Protocol):
    def load(self) -> DataStore: ...
    def save(self, store: DataStore) -> None: ...
    def ping(self) -> bool: ...
    def business_overview(self) -> dict[str, int]: ...
